### PR TITLE
Implement .all()

### PR DESCRIPTION
**Pull request by djiordhan**
Get all current active sessions. This function returns cursor so forEach will be needed when iteration the sessions.

### CODE REVIEW

**Comment by jdesboeufs** [comment]
Can you add some test?

**Comment by djiordhan** [comment]
Hi I added test_all spec to legacy_test.js, it checks the newly inserted session under store.all function. It passed when I ran npm test in my machine but it failed in travis-ci 2 and 3rd tests. 

I even removed the spec but still its failing, it says it has something to do with mongoose version cannot see 'Server' of mongodb 1.4.40 version.

**Comment by djiordhan** [comment]
The connect-redis returns the session as array instead of cursor. I will implement this as well.

**Comment by djiordhan** [comment]
✓ test_all

The test all passed in my machine and in travis-ci, but still theres an error about mongoose.

**Comment by adarrra** [comment]
hi! maybe give this PR one more chance? Kind a useful method

**Comment by mingchuno** [comment]
done in #291

**Pull request closed without merging**
