### PR TITLE
crypto: fixes & updates

### PR DESCRIPTION
**Pull request by jas-**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature, Bug fix

- **What is the current behavior?** (You can also link to an open issue here)
Buggy crypto object parsing

- **What is the new behavior (if this is a feature change)?**
- Upgraded dependency to v3.0.0 to use ASN.1 output
- Option change for crypto from hex to base64 encoding
- Trap parse errors on .get() operations

- **Other information**:

- **Checklist:**

- [ ] Added test cases
- [ ] Updated changelog

### CODE REVIEW

**Comment by mingchuno** [comment]
@jas- I have fixed and created a patch for you to apply (since I cannot commit and push to your branch)

**Comment by mingchuno** [comment]
@jas- You can cherry-pick this commit: https://github.com/jdesboeufs/connect-mongo/commit/daff9edebf3e4f003e392f68b8e0f35bcf54a3c0

**Comment by jas-** [comment]
Tracked in #395

**Comment by mingchuno** [comment]
I have fixed and CI passed in my branch. I have merged.

**Pull request closed without merging**
