### PR TITLE
fix: move mongodb to peerDependencies

### PR DESCRIPTION
**Pull request by rfox12**
In order to allow `connect-mongo` to adapt to internal Typescript changes (that do not break the interface), we can specify `mongodb` as a peer dependency--allowing end users to use any version of mongodb they want as long as it's a minor release of driver version 4.1.x

Should close issue: https://github.com/jdesboeufs/connect-mongo/issues/434#issue-979635109 and issue https://github.com/jdesboeufs/connect-mongo/issues/433#issue-976785292 and https://github.com/jdesboeufs/connect-mongo/issues/436#issue-981684458

### CODE REVIEW

**Comment by rfox12** [comment]
@mingchuno I finally got around to finishing out this PR.  All 23 tests passed for both version 4.1.0 and 4.1.1 versions of the `mongodb` driver.  So this PR should fix problems that people are having with Typescript types being incompatible (regardless of whether they are on 4.1.0 or 4.1.1).  And hopefully this means we don't have to worry about the changes when 4.1.2 (or whatever) is released.

The way you test a peer dependency is to also include the peer version you want to test in your `devDependencies` section of the `package.json`.   So in this case, I tested both 4.1.0 and 4.1.1 of `mongodb` by making that change and building / testing twice.

Please take a look, I think this is ready for release?

**Comment by lmeerma** [comment]
Any update when this will be merged?

**Comment by rfox12** [comment]
@mingchuno My organization is happy to be a maintainer of connect-mongo.  We rely on it.

**Review by mingchuno — APPROVED** [review]
PR LGTM

**Comment by mingchuno** [comment]
@rfox12 Well, I am also a random guy out there that are using this repo and found it is unmaintained. So I ask @jdesboeufs if I can pick it up. I will tried to be here more often. Sadly, I don't have the admin access of this repo too.

**Pull request merged**
