### PR TITLE
Types

### LINKED ISSUE #355: types.d.ts has a hard dependency on mongoose, which is optional.
Mongoose is used in types definitions, but the mongoose library itself is not required by the package.

### PR DESCRIPTION
**Pull request by vansergen**
## Changes

- Move `@types/express-session` to dependencies
- Move `@types/mongoose` to dependencies
- Remove `@types/express` from devDependencies
- Remove `@types/mongodb` from devDependencies
- Add `prettier-config-standard` to devDependencies

### Other changes

- Update tests 6a2f529
- Add Node 14 to Travis CI bbc8993

Fixes #355

### CODE REVIEW

**Comment by vansergen** [comment]
@jaredhanson Do you have any plans to review this PR?

**Comment by mingchuno** [comment]
@vansergen can you split the PR into few parts? 
1. eslint and listing update
2. add node 14 support in CI
3. Update the @type depns. (this should be the last one since we may still need to discuss the best options?)

I will handle the first 2 first

**Comment by vansergen** [comment]
@mingchuno ok, Here is the CI update #364

**Comment by vansergen** [comment]
@mingchuno Did you have a chance to look at it?

**Comment by guyellis** [comment]
@vansergen - I think that this PR is still a mixture of multiple PRs. There are (1) functional code changes and (2) stylistic formatting mixed in the same PR. I think that those 2 need to be separated out and if possible the PRs should be smaller. The `noop` style changes should be by themselves. First check with the repo owner that they want those style/formatting changes.

**Comment by cerireyhan** [comment]
Is there any progress on this? Currently getting lots of type errors related to express-session and mongoose connection.

**Comment by mingchuno** [comment]
I am planning to rewrite the lib in typescript

**Comment by mingchuno** [comment]
@vansergen I have just rewrite the library in TS and already included your check. Please install and test out! https://www.npmjs.com/package/connect-mongo

**Pull request closed without merging**
