### PR TITLE
Add option writeOperationOptions: options object to pass to every MongoDB write operation call that supports it (e.g. update, remove)

### PR DESCRIPTION
**Pull request by nikwen**
Useful for adjusting the write concern.

### CODE REVIEW

**Comment by nikwen** [comment]
@jdesboeufs Any chance that this might be merged? :)

**Comment by nikwen** [comment]
Rebased on the current master, so no merge conflicts anymore.

@jdesboeufs Could we get this merged? :)

**Comment by mingchuno** [comment]
@nikwen sorry for late reply, can you rebase again?

**Comment by nikwen** [comment]
@mingchuno Rebased. Please merge it as soon as possible as I will not rebase yet another time. Thank you! :blush:

**Comment by nikwen** [comment]
Thanks for merging! :)

**Pull request merged**
