### PR TITLE
Transparent crypto support

### PR DESCRIPTION
**Pull request by jas-**
The following functionality is included:
 - Symmetric encryption of session data following OWASP recommendations.
 - Updates to readme providing crypto options
 - Key derivation to strengthen provided secret in accordance with NIST SP 800-108 & 800-56c
 - Unique IV conforming to RFC 4309 & NIST SP 800-38d
 - Support for varying symmetric algorithms, key, iv & authentication tag sizes, hashing algorithms & ciphertext encoding
 - Test harness for crypto class as well as using transparent crypto functionality

### CODE REVIEW

**Comment by jas-** [comment]
My apologies on the two updates since the original PR, had a typo and neglected removal of a debug statement.

**Comment by mingchuno** [comment]
LGTM
@jdesboeufs , any comment?

**Comment by luislobo** [comment]
@jas- @mingchuno 
Is it a requirement to delete the `secret` from the passed in options object? this is breaking some use cases, for example in `sails` (check https://github.com/balderdashy/sails/issues/6810 and  https://github.com/navicstein/session-dep )

It can probably be work arounded in sails session management, but I'd like to understand if there is actually a requirement to delete an attribute of the passing object (and I don't see that is documented anywhere neither)

Thank you!

**Comment by jas-** [comment]
@luislobo Interesting, I didn't get any notification on this comment for some reason. It is not a requirement, just trying to protect the original value in memory.

**Pull request merged**
