### PR TITLE
Crypto

### PR DESCRIPTION
**Pull request by jas-**
To ensure a robust set of crypto algorithms, modes, key sizes and key derivations are available the original crypto class contributed has been refactored as the [kruptein](https://www.npmjs.com/package/kruptein) module.

In addition to greater flexibility for crypto options it was also designed to conform to industry standards for key management, key sizes, iv randomization etc etc.

### CODE REVIEW

**Comment by jas-** [comment]
@mingchuno, @jdesboeufs have either you had a chance to look this over or should I add more tests to keep the coveralls score higher?

**Comment by jas-** [comment]
@mingchuno the bot marked this ‘won’t fix’, is that right?

**Comment by mingchuno** [comment]
Sorry for stale the PR ... bot auto mark it as stale ...

**Comment by mingchuno** [comment]
I have doubt about adding extra depns and should we add that much crypto-related logic in the lib .. ?

**Comment by jas-** [comment]
The module was actually created because I started adding crypto support to a few other session stores. This way not only is the crypto implemented done to the standards it also is easier for me to maintain one module vs trying to keep abreast of the crypto support previously added.

**Comment by jas-** [comment]
If I add more test cases to improve the coveralls report would that get this merged?

**Comment by jas-** [comment]
@mingchuno Good morning, I hope things are going well. I am going to add additional tests to bring the coverage scores up. Because I have made other contributions to session stores with regards to transparent encryption/decryption support, rolling up that code into a module helps ensure I keep maintain those contributions easier to keep abreast of bug fixes etc.

**Comment by mingchuno** [comment]
Can you refer me to the contributions to other session stores?

**Comment by jas-** [comment]
Good morning,

Right now I have a total of five; four of which are awaiting integration (including this one) and the other that is using the module is the [session-file-store](https://www.npmjs.com/package/session-file-store) middleware.

I am working on the test harness (if you haven't noticed) to bring the coveralls score back up.

**Comment by jas-** [comment]
Anything additional to get this merged?

**Comment by jas-** [comment]
Opened issue #372 to address PR.

**Comment by jas-** [comment]
Re-opened

**Comment by mingchuno** [comment]
@jas- I have just rewrite the library in TS and already included your check. Please install and test out! https://www.npmjs.com/package/connect-mongo

**Comment by jas-** [comment]
This PR is no longer applicable

**Pull request closed without merging**
